### ISSUE TITLE
Key

### ISSUE THREAD

**Issue by Exilr** [johnnyon-thespot/PiratedHeat#1]
The key won't work. Been copying and pasting but it says that it is invalid. What do i do?

**Comment by johnnyon-thespot** [comment]
It just worked for me with a new generated key. Make sure you paste it and has no spaces in the end. Lmk if it still occurs

**Comment by Exilr** [comment]
Still won't work.
   
![image](https://github.com/johnnyon-thespot/PiratedHeat/assets/174769929/dafbcf7e-c857-417c-a234-07761400e225)

**Comment by Exilr** [comment]
![image](https://github.com/johnnyon-thespot/PiratedHeat/assets/174769929/62392b9c-e94f-4edb-8762-87a917e1d0f8)

**Comment by Exilr** [comment]
ISSUE HAS BEEN RESOLVED
